spring:
  application:
    name: deployment

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info

aws:
  region: "eu-central-1"
  s3:
    bucket-name: j3-service-bucket-${ENV}
  dynamoDb:
    table-name: j3_payloads_metadata-${ENV}
  sqs:
    queue-url: https://sqs.eu-central-1.amazonaws.com/143936507261/j3-queue-${ENV}