spring:
  application:
    name: deployment

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info

aws:
  region: ${REGION}
  s3:
    bucket-name: j3-service-bucket-${REGION}-${ENV}
  dynamoDb:
    table-name: j3_payloads_metadata-${REGION}-${ENV}
  sqs:
    queue-url: https://sqs.${REGION}.amazonaws.com/143936507261/j3-queue-${REGION}-${ENV}

env-dependent-value: default value