spring:
  application:
    name: deployment

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info

aws:
  region: "eu-central-1"
  s3:
    bucket-name: "j3-service-bucket"
